api/urls.py
from django.contrib import admin
from django.urls import path
from api import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='user_login'),
    path('problem_list/', views.problem_list, name='problem_list'),
    path('problem_create/', views.problem_create, name='problem_create'),
    path('problem/<int:problem_id>', views.problem_details, name='problem_details'),


]

problemList/urls.py
from django.contrib import admin
from django.urls import path, include

import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls'))
]

api/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
PRIORITY_CHOICES = [
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
]


class Problem(models.Model):
    name = models.CharField(max_length=60),
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    description = models.TextField()
    age = models.IntegerField(default=0)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, default='In_progress')
    solution = models.TextField(default="no solution yet")
    assigned_user = models.ForeignKey(User,null=True,on_delete=models.CASCADE, related_name='assigned_user')
    resolved_user = models.ForeignKey(User, null=True ,on_delete=models.CASCADE, related_name='resolved_user')

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()

    # def __str__(self):
    #     return self.name

# class Group
# Aa1234567891!

api/forms.py
from django import forms
from api.models import Problem


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        exclude = ['reported_by', 'date_of_creation','status','solution','resolved_user']


class SolutionForm(forms.Form):
    solution = forms.CharField()

api/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from api.forms import UserLoginForm, ProblemForm, SolutionForm
from api.models import Problem


# Create your views here.


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if username == '123':
                return render(request, 'problem_create.html')
            if user:
                login(request, user)
                # return redirect('problem_list')
                return render(request, 'problem_list.html')
            else:
                redirect('problem_create')
    else:
        form = UserLoginForm()
    return render(request, 'login.html', {'form': form})


def problem_list(request):
    user = request.user
    problems = Problem.objects.filter(assigned_user=user) #фильтурет проблемы, чтобы получить только те, которые связаны именно с определенным пользоватлем
    return render(request, 'problem_list.html', {'problems': problems,'user':user})


def problem_create(request):
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            problem.save()
            return redirect('problem_list')
    else:
        form = ProblemForm()
    return render(request, 'problem_create.html', {'form':form})




def problem_details(request, problem_id):
    problem = Problem.objects.get(id=problem_id)
    if request.method == "POST":
        form = SolutionForm(request.POST)
        if form.is_valid(): #для проверки валидации
            solution = form.cleaned_data['solution']
            problem.solution = solution
            problem.resolved_user = request.user
            problem.status = "completed"
            problem.save()
            redirect('problem_list')
    else:
        form = SolutionForm()
    return render(request, 'problem_details.html', {'problem': problem, 'form':form})

def home(request):
    return render(request, 'home.html')

api/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <a href="{% url 'user_login' %}"><button id="loginButton">Login</button></a>
    <a href="{% url 'problem_create' %}"><button id="createProblemButton">Create Problem</button></a>
</body>
</html>

api/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h1>User Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
</body>
</html>

api/templates/problem_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Problem</title>
</head>
<body>
    <h1>Create a New Problem</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

api/templates/problem_details.html
<!DOCTYPE html>
<html>
<head>
    <title>Problem Details</title>
</head>
<body>
    <h1>Problem Details</h1>
    <h2>Problem Name: {{ problem.name }}</h2>
        <h3>Problem Description: {{ problem.description }}</h3>
    <strong>Telephone:</strong> {{ problem.telephone }}<br>
        <strong>Email:</strong> {{ problem.email }}<br>
        <strong>Description:</strong> {{ problem.description }}<br>
        <strong>Date of Creation:</strong> {{ problem.date_of_creation }}<br>
        <strong>Status: {{ problem.status }}</strong>

    {% if problem.status != "completed" %}
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    {% endif %}
</body>
</html>

api/templates/problem_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Problem List</title>
</head>
<body>
    <h1>Problem List</h1>
 {% comment %}   {% if user %}
        <h2>Welcome {% user.username %}</h2>
    {% endif %}{% endcomment %}
    <ul>
        {% for problem in problems %}
            {% if problem.status == 'In_progress' %}
                <a href="{% url 'problem_details' problem.id %}">
                <li>
                <strong>Name:</strong> {{ problem.name }}<br>
                <strong>Priority:</strong> {{ problem.get_priority_display }}<br>
            </li>
                </a>
            {% endif %}
        {% empty %}
            <p>No problems found.</p>
        {% endfor %}
    </ul>
</body>
</html>